{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-08-21T00:00:00Z",
  "bugzilla": {
    "description": "kernel: nfc: pn533: Wait for out_urb's completion in pn533_usb_send_frame()",
    "id": "2306435",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2306435"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-416",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-52907",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nnfc: pn533: Wait for out_urb's completion in pn533_usb_send_frame()\nFix a use-after-free that occurs in hcd when in_urb sent from\npn533_usb_send_frame() is completed earlier than out_urb. Its callback\nfrees the skb data in pn533_send_async_complete() that is used as a\ntransfer buffer of out_urb. Wait before sending in_urb until the\ncallback of out_urb is called. To modify the callback of out_urb alone,\nseparate the complete function of out_urb and ack_urb.\nFound by a modified version of syzkaller.\nBUG: KASAN: use-after-free in dummy_timer\nCall Trace:\nmemcpy (mm/kasan/shadow.c:65)\ndummy_perform_transfer (drivers/usb/gadget/udc/dummy_hcd.c:1352)\ntransfer (drivers/usb/gadget/udc/dummy_hcd.c:1453)\ndummy_timer (drivers/usb/gadget/udc/dummy_hcd.c:1972)\narch_static_branch (arch/x86/include/asm/jump_label.h:27)\nstatic_key_false (include/linux/jump_label.h:207)\ntimer_expire_exit (include/trace/events/timer.h:127)\ncall_timer_fn (kernel/time/timer.c:1475)\nexpire_timers (kernel/time/timer.c:1519)\n__run_timers (kernel/time/timer.c:1790)\nrun_timer_softirq (kernel/time/timer.c:1803)"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-52907\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-52907\nhttps://lore.kernel.org/linux-cve-announce/2024082114-CVE-2023-52907-faaf@gregkh/T"
  ]
}