{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2025-01-21T00:00:00Z",
  "bugzilla": {
    "description": "kernel: net/mlx5: Fix variable not being completed when function returns",
    "id": "2339138",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2339138"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2025-21662",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nnet/mlx5: Fix variable not being completed when function returns\nWhen cmd_alloc_index(), fails cmd_work_handler() needs\nto complete ent-\u003eslotted before returning early.\nOtherwise the task which issued the command may hang:\nmlx5_core 0000:01:00.0: cmd_work_handler:877:(pid 3880418): failed to allocate command entry\nINFO: task kworker/13:2:4055883 blocked for more than 120 seconds.\nNot tainted 4.19.90-25.44.v2101.ky10.aarch64 #1\n\"echo 0 \u003e /proc/sys/kernel/hung_task_timeout_secs\" disables this message.\nkworker/13:2    D    0 4055883      2 0x00000228\nWorkqueue: events mlx5e_tx_dim_work [mlx5_core]\nCall trace:\n__switch_to+0xe8/0x150\n__schedule+0x2a8/0x9b8\nschedule+0x2c/0x88\nschedule_timeout+0x204/0x478\nwait_for_common+0x154/0x250\nwait_for_completion+0x28/0x38\ncmd_exec+0x7a0/0xa00 [mlx5_core]\nmlx5_cmd_exec+0x54/0x80 [mlx5_core]\nmlx5_core_modify_cq+0x6c/0x80 [mlx5_core]\nmlx5_core_modify_cq_moderation+0xa0/0xb8 [mlx5_core]\nmlx5e_tx_dim_work+0x54/0x68 [mlx5_core]\nprocess_one_work+0x1b0/0x448\nworker_thread+0x54/0x468\nkthread+0x134/0x138\nret_from_fork+0x10/0x18"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2025-21662\nhttps://nvd.nist.gov/vuln/detail/CVE-2025-21662\nhttps://lore.kernel.org/linux-cve-announce/2025012134-CVE-2025-21662-0c72@gregkh/T"
  ]
}