{
  "document": {
    "aggregate_severity": {
      "namespace": "https://access.redhat.com/security/updates/classification/",
      "text": "Low"
    },
    "category": "csaf_vex",
    "csaf_version": "2.0",
    "distribution": {
      "text": "Copyright © Red Hat, Inc. All rights reserved.",
      "tlp": {
        "label": "WHITE",
        "url": "https://www.first.org/tlp/"
      }
    },
    "lang": "en",
    "notes": [
      {
        "category": "legal_disclaimer",
        "text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
        "title": "Terms of Use"
      }
    ],
    "publisher": {
      "category": "vendor",
      "contact_details": "https://access.redhat.com/security/team/contact/",
      "issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
      "name": "Red Hat Product Security",
      "namespace": "https://www.redhat.com"
    },
    "references": [
      {
        "category": "self",
        "summary": "Canonical URL",
        "url": "https://security.access.redhat.com/data/csaf/v2/vex/2015/cve-2015-5159.json"
      }
    ],
    "title": "python-kdcproxy: Missing request size limit allows denial of service",
    "tracking": {
      "current_release_date": "2025-01-07T17:01:36+00:00",
      "generator": {
        "date": "2025-01-07T17:01:36+00:00",
        "engine": {
          "name": "Red Hat SDEngine",
          "version": "4.2.5"
        }
      },
      "id": "CVE-2015-5159",
      "initial_release_date": "2015-07-21T00:00:00+00:00",
      "revision_history": [
        {
          "date": "2015-07-21T00:00:00+00:00",
          "number": "1",
          "summary": "Initial version"
        },
        {
          "date": "2023-05-12T10:41:18+00:00",
          "number": "2",
          "summary": "Current version"
        },
        {
          "date": "2025-01-07T17:01:36+00:00",
          "number": "3",
          "summary": "Last generated version"
        }
      ],
      "status": "final",
      "version": "3"
    }
  },
  "product_tree": {
    "branches": [
      {
        "branches": [
          {
            "branches": [
              {
                "category": "product_name",
                "name": "Red Hat Enterprise Linux 7",
                "product": {
                  "name": "Red Hat Enterprise Linux 7",
                  "product_id": "red_hat_enterprise_linux_7",
                  "product_identification_helper": {
                    "cpe": "cpe:/o:redhat:enterprise_linux:7"
                  }
                }
              }
            ],
            "category": "product_family",
            "name": "Red Hat Enterprise Linux 7"
          },
          {
            "category": "product_version",
            "name": "python-kdcproxy",
            "product": {
              "name": "python-kdcproxy",
              "product_id": "python-kdcproxy",
              "product_identification_helper": {
                "purl": "pkg:rpm/redhat/python-kdcproxy?arch=src"
              }
            }
          }
        ],
        "category": "vendor",
        "name": "Red Hat"
      }
    ],
    "relationships": [
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python-kdcproxy as a component of Red Hat Enterprise Linux 7",
          "product_id": "red_hat_enterprise_linux_7:python-kdcproxy"
        },
        "product_reference": "python-kdcproxy",
        "relates_to_product_reference": "red_hat_enterprise_linux_7"
      }
    ]
  },
  "vulnerabilities": [
    {
      "cve": "CVE-2015-5159",
      "cwe": {
        "id": "CWE-400",
        "name": "Uncontrolled Resource Consumption"
      },
      "discovery_date": "2015-07-21T00:00:00+00:00",
      "flags": [
        {
          "label": "vulnerable_code_not_present",
          "product_ids": [
            "red_hat_enterprise_linux_7:python-kdcproxy"
          ]
        }
      ],
      "ids": [
        {
          "system_name": "Red Hat Bugzilla ID",
          "text": "1245200"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
          "title": "Vulnerability description"
        },
        {
          "category": "summary",
          "text": "python-kdcproxy: Missing request size limit allows denial of service",
          "title": "Vulnerability summary"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "known_not_affected": [
          "red_hat_enterprise_linux_7:python-kdcproxy"
        ]
      },
      "references": [
        {
          "category": "self",
          "summary": "Canonical URL",
          "url": "https://access.redhat.com/security/cve/CVE-2015-5159"
        },
        {
          "category": "external",
          "summary": "RHBZ#1245200",
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
        },
        {
          "category": "external",
          "summary": "https://www.cve.org/CVERecord?id=CVE-2015-5159",
          "url": "https://www.cve.org/CVERecord?id=CVE-2015-5159"
        },
        {
          "category": "external",
          "summary": "https://nvd.nist.gov/vuln/detail/CVE-2015-5159",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2015-5159"
        }
      ],
      "release_date": "2015-07-21T00:00:00+00:00",
      "remediations": [
        {
          "category": "workaround",
          "details": "Add “LimitRequestBody 100000” to the \u003cLocation\u003e stanza, like this:\n\n    \u003cLocation \"/KdcProxy\"\u003e\n        Satisfy Any\n        Order Deny,Allow\n        Allow from all\n        WSGIProcessGroup kdcproxy\n        WSGIApplicationGroup kdcproxy\n        LimitRequestBody 100000\n    \u003c/Location\u003e",
          "product_ids": [
            "red_hat_enterprise_linux_7:python-kdcproxy"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v2": {
            "version": "2.0",
            "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "accessVector": "NETWORK",
            "accessComplexity": "LOW",
            "authentication": "NONE",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "availabilityImpact": "PARTIAL",
            "baseScore": 5
          },
          "products": [
            "red_hat_enterprise_linux_7:python-kdcproxy"
          ]
        }
      ],
      "threats": [
        {
          "category": "impact",
          "details": "Low",
          "product_ids": [
            "red_hat_enterprise_linux_7:python-kdcproxy"
          ]
        }
      ],
      "title": "python-kdcproxy: Missing request size limit allows denial of service"
    }
  ]
}