{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2025-02-26T00:00:00Z",
  "bugzilla": {
    "description": "kernel: f2fs: fix to do sanity check on block address in f2fs_do_zero_range()",
    "id": "2348162",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2348162"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49363",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nf2fs: fix to do sanity check on block address in f2fs_do_zero_range()\nAs Yanming reported in bugzilla:\nhttps://bugzilla.kernel.org/show_bug.cgi?id=215894\nI have encountered a bug in F2FS file system in kernel v5.17.\nI have uploaded the system call sequence as case.c, and a fuzzed image can\nbe found in google net disk\nThe kernel should enable CONFIG_KASAN=y and CONFIG_KASAN_INLINE=y. You can\nreproduce the bug by running the following commands:\nkernel BUG at fs/f2fs/segment.c:2291!\nCall Trace:\nf2fs_invalidate_blocks+0x193/0x2d0\nf2fs_fallocate+0x2593/0x4a70\nvfs_fallocate+0x2a5/0xac0\nksys_fallocate+0x35/0x70\n__x64_sys_fallocate+0x8e/0xf0\ndo_syscall_64+0x3b/0x90\nentry_SYSCALL_64_after_hwframe+0x44/0xae\nThe root cause is, after image was fuzzed, block mapping info in inode\nwill be inconsistent with SIT table, so in f2fs_fallocate(), it will cause\npanic when updating SIT with invalid blkaddr.\nLet's fix the issue by adding sanity check on block address before updating\nSIT table with it."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49363\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49363\nhttps://lore.kernel.org/linux-cve-announce/2025022644-CVE-2022-49363-a93a@gregkh/T"
  ]
}