{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-10-21T00:00:00Z",
  "bugzilla": {
    "description": "kernel: s390/qeth: fix use-after-free in hsci",
    "id": "2320712",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2320712"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-416",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-48954",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\ns390/qeth: fix use-after-free in hsci\nKASAN found that addr was dereferenced after br2dev_event_work was freed.\n==================================================================\nBUG: KASAN: use-after-free in qeth_l2_br2dev_worker+0x5ba/0x6b0\nRead of size 1 at addr 00000000fdcea440 by task kworker/u760:4/540\nCPU: 17 PID: 540 Comm: kworker/u760:4 Tainted: G            E      6.1.0-20221128.rc7.git1.5aa3bed4ce83.300.fc36.s390x+kasan #1\nHardware name: IBM 8561 T01 703 (LPAR)\nWorkqueue: 0.0.8000_event qeth_l2_br2dev_worker\nCall Trace:\n[\u003c000000016944d4ce\u003e] dump_stack_lvl+0xc6/0xf8\n[\u003c000000016942cd9c\u003e] print_address_description.constprop.0+0x34/0x2a0\n[\u003c000000016942d118\u003e] print_report+0x110/0x1f8\n[\u003c0000000167a7bd04\u003e] kasan_report+0xfc/0x128\n[\u003c000000016938d79a\u003e] qeth_l2_br2dev_worker+0x5ba/0x6b0\n[\u003c00000001673edd1e\u003e] process_one_work+0x76e/0x1128\n[\u003c00000001673ee85c\u003e] worker_thread+0x184/0x1098\n[\u003c000000016740718a\u003e] kthread+0x26a/0x310\n[\u003c00000001672c606a\u003e] __ret_from_fork+0x8a/0xe8\n[\u003c00000001694711da\u003e] ret_from_fork+0xa/0x40\nAllocated by task 108338:\nkasan_save_stack+0x40/0x68\nkasan_set_track+0x36/0x48\n__kasan_kmalloc+0xa0/0xc0\nqeth_l2_switchdev_event+0x25a/0x738\natomic_notifier_call_chain+0x9c/0xf8\nbr_switchdev_fdb_notify+0xf4/0x110\nfdb_notify+0x122/0x180\nfdb_add_entry.constprop.0.isra.0+0x312/0x558\nbr_fdb_add+0x59e/0x858\nrtnl_fdb_add+0x58a/0x928\nrtnetlink_rcv_msg+0x5f8/0x8d8\nnetlink_rcv_skb+0x1f2/0x408\nnetlink_unicast+0x570/0x790\nnetlink_sendmsg+0x752/0xbe0\nsock_sendmsg+0xca/0x110\n____sys_sendmsg+0x510/0x6a8\n___sys_sendmsg+0x12a/0x180\n__sys_sendmsg+0xe6/0x168\n__do_sys_socketcall+0x3c8/0x468\ndo_syscall+0x22c/0x328\n__do_syscall+0x94/0xf0\nsystem_call+0x82/0xb0\nFreed by task 540:\nkasan_save_stack+0x40/0x68\nkasan_set_track+0x36/0x48\nkasan_save_free_info+0x4c/0x68\n____kasan_slab_free+0x14e/0x1a8\n__kasan_slab_free+0x24/0x30\n__kmem_cache_free+0x168/0x338\nqeth_l2_br2dev_worker+0x154/0x6b0\nprocess_one_work+0x76e/0x1128\nworker_thread+0x184/0x1098\nkthread+0x26a/0x310\n__ret_from_fork+0x8a/0xe8\nret_from_fork+0xa/0x40\nLast potentially related work creation:\nkasan_save_stack+0x40/0x68\n__kasan_record_aux_stack+0xbe/0xd0\ninsert_work+0x56/0x2e8\n__queue_work+0x4ce/0xd10\nqueue_work_on+0xf4/0x100\nqeth_l2_switchdev_event+0x520/0x738\natomic_notifier_call_chain+0x9c/0xf8\nbr_switchdev_fdb_notify+0xf4/0x110\nfdb_notify+0x122/0x180\nfdb_add_entry.constprop.0.isra.0+0x312/0x558\nbr_fdb_add+0x59e/0x858\nrtnl_fdb_add+0x58a/0x928\nrtnetlink_rcv_msg+0x5f8/0x8d8\nnetlink_rcv_skb+0x1f2/0x408\nnetlink_unicast+0x570/0x790\nnetlink_sendmsg+0x752/0xbe0\nsock_sendmsg+0xca/0x110\n____sys_sendmsg+0x510/0x6a8\n___sys_sendmsg+0x12a/0x180\n__sys_sendmsg+0xe6/0x168\n__do_sys_socketcall+0x3c8/0x468\ndo_syscall+0x22c/0x328\n__do_syscall+0x94/0xf0\nsystem_call+0x82/0xb0\nSecond to last potentially related work creation:\nkasan_save_stack+0x40/0x68\n__kasan_record_aux_stack+0xbe/0xd0\nkvfree_call_rcu+0xb2/0x760\nkernfs_unlink_open_file+0x348/0x430\nkernfs_fop_release+0xc2/0x320\n__fput+0x1ae/0x768\ntask_work_run+0x1bc/0x298\nexit_to_user_mode_prepare+0x1a0/0x1a8\n__do_syscall+0x94/0xf0\nsystem_call+0x82/0xb0\nThe buggy address belongs to the object at 00000000fdcea400\nwhich belongs to the cache kmalloc-96 of size 96\nThe buggy address is located 64 bytes inside of\n96-byte region [00000000fdcea400, 00000000fdcea460)\nThe buggy address belongs to the physical page:\npage:000000005a9c26e8 refcount:1 mapcount:0 mapping:0000000000000000 index:0x0 pfn:0xfdcea\nflags: 0x3ffff00000000200(slab|node=0|zone=1|lastcpupid=0x1ffff)\nraw: 3ffff00000000200 0000000000000000 0000000100000122 000000008008cc00\nraw: 0000000000000000 0020004100000000 ffffffff00000001 0000000000000000\npage dumped because: kasan: bad access detected\nMemory state around the buggy address:\n00000000fdcea300: fb fb fb fb fb fb fb fb fb fb fb fb fc fc fc fc\n00000000fdcea380: fb fb fb fb fb fb f\n---truncated---"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-48954\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-48954\nhttps://lore.kernel.org/linux-cve-announce/2024102141-CVE-2022-48954-30f2@gregkh/T"
  ]
}